import type { NewTheme } from "../models/themes";

export const SEED_THEMES: NewTheme[] = [
  {
    name: "Chai",
    slug: "chai",
    category: "Community",
    description: "Warm amber, cream, Lora serif. Feels like a hug that also collects data.",
    config: {
      background: "#FBF5EC",
      surface: "#FFFFFF",
      surfaceAlt: "#F4E9D7",
      text: "#3B2A1A",
      textMuted: "#7A6755",
      accent: "#B8722E",
      accentText: "#FFFFFF",
      border: "#E5D5BD",
      error: "#B8261A",
      fontFamily: "'Lora', Georgia, serif",
      fontUrl: "https://fonts.googleapis.com/css2?family=Lora:wght@400;600;700&display=swap",
      headingWeight: 700,
      borderRadius: "md",
      logoEmoji: "🍵",
    },
  },
  {
    name: "Matrix",
    slug: "matrix",
    category: "Movie",
    description: "Black bg, neon green, Fira Code. Your form looks like it's hacking something.",
    config: {
      background: "#000000",
      surface: "#0A0F0A",
      surfaceAlt: "#11181A",
      text: "#00FF41",
      textMuted: "#5BA663",
      accent: "#00FF41",
      accentText: "#000000",
      border: "#173A20",
      error: "#FF1744",
      fontFamily: "'Fira Code', monospace",
      fontUrl:
        "https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;500;600&display=swap",
      headingWeight: 600,
      borderRadius: "none",
      logoEmoji: "🟢",
    },
  },
  {
    name: "Naruto Run",
    slug: "naruto-run",
    category: "Anime",
    description: "Orange/navy, Bebas Neue headers, subtle kunai pattern. Fills form at 100mph.",
    config: {
      background: "#0F1E3D",
      surface: "#152A52",
      surfaceAlt: "#1E3666",
      text: "#FFE7C7",
      textMuted: "#A9B7D6",
      accent: "#FF7A1A",
      accentText: "#0F1E3D",
      border: "#2A4480",
      error: "#FF4D4D",
      fontFamily: "'Bebas Neue', 'Inter', sans-serif",
      fontUrl:
        "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Inter:wght@400;600&display=swap",
      headingWeight: 400,
      borderRadius: "sm",
      logoEmoji: "🍥",
    },
  },
  {
    name: "Cyberpunk 2025",
    slug: "cyberpunk-2025",
    category: "Game",
    description: "Dark purple, neon pink/yellow, Rajdhani. Still buggy. On purpose.",
    config: {
      background: "#0B0420",
      surface: "#180A36",
      surfaceAlt: "#241149",
      text: "#FFF15C",
      textMuted: "#D6B6FF",
      accent: "#FF2A6D",
      accentText: "#FFFFFF",
      border: "#4F2BB3",
      error: "#FF2A6D",
      fontFamily: "'Rajdhani', 'Inter', sans-serif",
      fontUrl:
        "https://fonts.googleapis.com/css2?family=Rajdhani:wght@400;500;700&display=swap",
      headingWeight: 700,
      borderRadius: "none",
      logoEmoji: "🌃",
    },
  },
  {
    name: "Minecraft Dirt Block",
    slug: "minecraft",
    category: "Game",
    description: "Earthy greens, pixelated border texture, VT323 font. Crafted with love.",
    config: {
      background: "#7CAC4D",
      surface: "#915B36",
      surfaceAlt: "#A77149",
      text: "#FFFFFF",
      textMuted: "#F5E2C9",
      accent: "#4B7A1F",
      accentText: "#FFFFFF",
      border: "#3A2818",
      error: "#D02F2F",
      fontFamily: "'VT323', monospace",
      fontUrl: "https://fonts.googleapis.com/css2?family=VT323&display=swap",
      headingWeight: 400,
      borderRadius: "none",
      logoEmoji: "⛏️",
    },
  },
  {
    name: "YC Orange",
    slug: "yc-orange",
    category: "Startup",
    description:
      "White, YC-orange accent, DM Sans. Comes pre-loaded with 'move fast' energy.",
    config: {
      background: "#FFFFFF",
      surface: "#FFFFFF",
      surfaceAlt: "#F7F7F5",
      text: "#1A1A1A",
      textMuted: "#6E6E6E",
      accent: "#FF6600",
      accentText: "#FFFFFF",
      border: "#E5E5E5",
      error: "#D03A2F",
      fontFamily: "'DM Sans', 'Inter', sans-serif",
      fontUrl:
        "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap",
      headingWeight: 700,
      borderRadius: "md",
      logoEmoji: "🟧",
    },
  },
  {
    name: "macOS Boring",
    slug: "macos-boring",
    category: "OS",
    description: "Frosted glass, system-ui font, subtle shadows. Judges will think it's native.",
    config: {
      background: "#F2F2F7",
      surface: "rgba(255,255,255,0.72)",
      surfaceAlt: "#E5E5EA",
      text: "#1C1C1E",
      textMuted: "#636366",
      accent: "#007AFF",
      accentText: "#FFFFFF",
      border: "#D1D1D6",
      error: "#FF3B30",
      fontFamily:
        "-apple-system, BlinkMacSystemFont, 'SF Pro Text', 'Inter', system-ui, sans-serif",
      fontUrl: "",
      headingWeight: 600,
      borderRadius: "lg",
      logoEmoji: "",
    },
  },
  {
    name: "Linux BTW",
    slug: "linux-btw",
    category: "OS",
    description:
      "Black bg, green text, Courier New. Monospace everything. No mouse required.",
    config: {
      background: "#000000",
      surface: "#0A0A0A",
      surfaceAlt: "#141414",
      text: "#33FF33",
      textMuted: "#6FCF6F",
      accent: "#33FF33",
      accentText: "#000000",
      border: "#1F4D1F",
      error: "#FF5555",
      fontFamily: "'Courier New', 'Fira Code', monospace",
      fontUrl: "",
      headingWeight: 700,
      borderRadius: "none",
      logoEmoji: "🐧",
    },
  },
  {
    name: "Film Noir",
    slug: "film-noir",
    category: "Movie",
    description:
      "Black/white/gold, Playfair Display, dramatic shadows. Every question feels like an interrogation.",
    config: {
      background: "#0A0A0A",
      surface: "#161616",
      surfaceAlt: "#1F1F1F",
      text: "#F4F1E6",
      textMuted: "#A39E8A",
      accent: "#C9A24B",
      accentText: "#0A0A0A",
      border: "#2A2A2A",
      error: "#D03A2F",
      fontFamily: "'Playfair Display', Georgia, serif",
      fontUrl:
        "https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;800&display=swap",
      headingWeight: 800,
      borderRadius: "sm",
      logoEmoji: "🎞️",
    },
  },
  {
    name: "Windows Vista (Unironic)",
    slug: "windows-vista",
    category: "OS",
    description:
      "Aero glass effect, Segoe UI, blue gradients. Nostalgia is a form of marketing.",
    config: {
      background: "#0B3D91",
      surface: "rgba(255,255,255,0.78)",
      surfaceAlt: "rgba(186,217,255,0.65)",
      text: "#0B2B5C",
      textMuted: "#3E5A86",
      accent: "#1F73E0",
      accentText: "#FFFFFF",
      border: "#A8C7FA",
      error: "#C8102E",
      fontFamily: "'Segoe UI', 'Inter', sans-serif",
      fontUrl: "",
      headingWeight: 600,
      borderRadius: "lg",
      logoEmoji: "🪟",
    },
  },
];
